### ISSUE TITLE
Error when executing boot_linux.sh

### ISSUE THREAD

**Issue by willthehuman** [SoulCipher/shofel2_linux#3]
Traceback (most recent call last):
  File "./shofel2.py", line 246, in <module>
    rcm = RCM()
  File "./shofel2.py", line 50, in __init__
    fds_before = get_fds()
  File "./shofel2.py", line 37, in get_fds
    return set(int(i) for i in os.listdir("/proc/self/fd"))
FileNotFoundError: [Errno 2] No such file or directory: '/proc/self/fd'

Detected. Waiting 5 seconds

./boot_linux.sh: line 15: ./imx_usb: cannot execute binary file

**Comment by Smethan** [comment]
Assuming you’re on Mac, try changing “/proc/self/fd” to “/dev/fd” on line 37 in shofel2.py, that fixed it for me
