### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by foen** [SoulCipher/shofel2_linux#4]
1) Turn off Switch
2) Ground right JoyCon rail PIN10 using paperclip JIG or JoyCon mod
3) Press VOL+ and connect USB cable to the Switch
-=-=--=--=--=-=-=-=-=--=-=-=-=-=-=-=-=--=-=-
Waiting for NVidia APX (Switch in RCM mode).
-=-=--=--=--=-=-=-=-=--=-=-=-=-=-=-=-=--=-=-

File descriptor: 9
b'c08405070000001800532c6401101062'
entry 400168ed
throwing more
Performing hax...
Size: 0x6c68

b'820000000000686c'
b'02000000000000000000000038e9aa01716c000000000000000000000000000000000000000000000f0f000000'
URB address: 0x1a96528
Traceback (most recent call last):
  File "./shofel2.py", line 247, in <module>
    rcm.pwn()
  File "./shofel2.py", line 205, in pwn
    s.ep0_read_unbounded(overwrite_len)
  File "./shofel2.py", line 76, in ep0_read_unbounded
    fcntl.ioctl(s.fd, USBDEVFS_SUBMITURB, urb)
OSError: [Errno 25] Inappropriate ioctl for device

Detected. Waiting 5 seconds

/lib64/ld-linux-x86-64.so.2: No such file or directory

Done. You should see kernel booting on switch soon

-//- kombos.org -//-

**Comment by blissirl** [comment]
For me this works - i see the Linux loader on the switch , however it stops short waiting for USB , cant figure out how to burn the SD image to the sd mmc tried win32 and poweriso - still switch sits waiting for the mmcblk0p2 or rootfs ? I know its something to do with the SD prep but im stumped.
